### ISSUE TITLE
你好能请教一下学习python的过程嘛

### ISSUE THREAD

**Issue by LarinaYelsu** [try2love/re-leetcode-from-zero#1]
我现在也在自学python，但是感觉没找到方向，感觉你的学习思路很好，能跟你请教一下嘛

**Comment by LarinaYelsu** [comment]
十分感谢你的建议😊我还想问一下你目前的话是有同时学c跟python对吗，我目前的话的想法也是跟你差不多想要在做中学，主要是感觉python的基础语法我已经学完了，不知道下一步该怎么做，有些迷茫，所以就想在github上找些项目实战跟着做





------------------ 原始邮件 ------------------
发件人: try2love ***@***.***&gt;
发送时间: 2024年11月19日 17:20
收件人: try2love/re-leetcode-from-zero ***@***.***&gt;
抄送: LarinaYelsu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [try2love/re-leetcode-from-zero] 你好能请教一下学习python的过程嘛 (Issue #1)





 
你好你好，我的思路是本科舍友推荐的，就是做中学，单纯看网课这种学习方法不适合我，因为我也曾尝试过跟着B站上的各种网课走过，发现几乎没有任何帮助，看网课对我来说纯属是感动自己耗时间罢了。本科舍友给我的建议就是去刷题，必须要主动去看题，想思路，主动去写代码，写不出来没关系，就去看参考答案，看看思路的差距在哪里，代码的差距在哪里。
 我是跟着代码随想录的题目编排走的，比较推荐，除了代码随想录的答案，也很推荐零茶山艾府的答案，零神的代码给人的感觉就是眼前一亮，一些好的代码方案都可以借鉴
 然后就是善用大模型，刚开始遇见不会的知识点很正常，我可是连从获取py列表长度/C++数组长度都不知道如何做的小白走过来的，遇到不会，不熟悉的知识点就去问大模型，我认为这是效率最高的方案了，我会选择把大模型的回答摘录下来到单独的一个文件里面（每个参考答案最后我都会有一个收获，单独的文件就是把收获全部放进去，也方便后续查找），这样组合拳走下来，我发现会的东西越来越多，需要记录的收获内容越来越少，效果很显著。重在坚持，不过讽刺的是我读了研后各种事务缠身，最终还是没能保证每日一题，更新频率越来越低，惭愧惭愧，不过学到的东西还是牢牢记在脑海里了🥳
 仅供参考，希望对你有帮助。

**Comment by LarinaYelsu** [comment]
你所说的大模型是ai是吗，是chatgpt还是国内的ai呀





------------------ 原始邮件 ------------------
发件人: try2love ***@***.***&gt;
发送时间: 2024年11月19日 17:20
收件人: try2love/re-leetcode-from-zero ***@***.***&gt;
抄送: LarinaYelsu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [try2love/re-leetcode-from-zero] 你好能请教一下学习python的过程嘛 (Issue #1)





 
你好你好，我的思路是本科舍友推荐的，就是做中学，单纯看网课这种学习方法不适合我，因为我也曾尝试过跟着B站上的各种网课走过，发现几乎没有任何帮助，看网课对我来说纯属是感动自己耗时间罢了。本科舍友给我的建议就是去刷题，必须要主动去看题，想思路，主动去写代码，写不出来没关系，就去看参考答案，看看思路的差距在哪里，代码的差距在哪里。
 我是跟着代码随想录的题目编排走的，比较推荐，除了代码随想录的答案，也很推荐零茶山艾府的答案，零神的代码给人的感觉就是眼前一亮，一些好的代码方案都可以借鉴
 然后就是善用大模型，刚开始遇见不会的知识点很正常，我可是连从获取py列表长度/C++数组长度都不知道如何做的小白走过来的，遇到不会，不熟悉的知识点就去问大模型，我认为这是效率最高的方案了，我会选择把大模型的回答摘录下来到单独的一个文件里面（每个参考答案最后我都会有一个收获，单独的文件就是把收获全部放进去，也方便后续查找），这样组合拳走下来，我发现会的东西越来越多，需要记录的收获内容越来越少，效果很显著。重在坚持，不过讽刺的是我读了研后各种事务缠身，最终还是没能保证每日一题，更新频率越来越低，惭愧惭愧，不过学到的东西还是牢牢记在脑海里了🥳
 仅供参考，希望对你有帮助。

**Comment by try2love** [comment]
我的不是实战项目哈，刷力扣主要是提升自己的编程能力，有一定能力了才做项目，我是这样想的。
大模型我用的是国产的kimi，已经相当成熟了，还不用梯子，你可以看我文件里面，后面的收获部分基本上都是让大模型生成的，质量很不错的。

**Comment by LarinaYelsu** [comment]
好的👌🏻明白了！！十分感谢！！！



------------------ 原始邮件 ------------------
发件人: try2love ***@***.***&gt;
发送时间: 2024年11月19日 17:40
收件人: try2love/re-leetcode-from-zero ***@***.***&gt;
抄送: LarinaYelsu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [try2love/re-leetcode-from-zero] 你好能请教一下学习python的过程嘛 (Issue #1)





 
我的不是实战项目哈，刷力扣主要是提升自己的编程能力，有一定能力了才做项目，我是这样想的。
 大模型我用的是国产的kimi，已经相当成熟了，还不用梯子，你可以看我文件里面，后面的收获部分基本上都是让大模型生成的，质量很不错的。
